use rust_decimal::Decimal;
use serde_json::Map as JsonMap;
use std::future::Future;

pub type JsonValue = serde_json::Value;
pub type JsonRow = JsonMap<String, JsonValue>;

/// Defines the supported database kinds.
pub enum DbKind {
    SQLite,
    PostgreSQL,
}

/// Defines the various error types that can be generated by rltbl_db.
#[derive(Clone, Debug)]
#[non_exhaustive] // We may add more specific error types in the future.
pub enum DbError {
    /// An error that occurred while connecting to a database.
    ConnectError(String),
    /// An error in the arguments to a function that accessed the database.
    InputError(String),
    /// An error in the data retrieved from the database.
    DataError(String),
    /// An error that originated from the database.
    DatabaseError(String),
}

impl std::error::Error for DbError {}

impl std::fmt::Display for DbError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            DbError::ConnectError(err)
            | DbError::DataError(err)
            | DbError::InputError(err)
            | DbError::DatabaseError(err) => write!(f, "{err}"),
        }
    }
}

/// Value types for [query parameters](Params)
#[derive(Debug, Clone)]
pub enum ParamValue {
    /// Represents a NULL value. Can be used with any column type.
    Null,
    /// Use with BOOL column types or equivalent.
    Boolean(bool),
    /// Use with INT2 column types or equivalent.
    SmallInteger(i16),
    /// Use with INT4 column types or equivalent.
    Integer(i32),
    /// Use with INT8 column types or equivalent.
    BigInteger(i64),
    /// Use with FLOAT4 column types or equivalent.
    Real(f32),
    /// Use with FLOAT8 column types or equivalent.
    BigReal(f64),
    /// Use with NUMERIC column types or equivalent.
    Numeric(Decimal),
    /// Use with TEXT and VARCHAR column types or equivalent.
    Text(String),
}

// Implementations of attempted conversions of various types into ParamValues:

impl From<&str> for ParamValue {
    fn from(item: &str) -> Self {
        ParamValue::Text(item.to_string())
    }
}

impl From<String> for ParamValue {
    fn from(item: String) -> Self {
        ParamValue::Text(item)
    }
}

impl From<&String> for ParamValue {
    fn from(item: &String) -> Self {
        ParamValue::Text(item.clone())
    }
}

impl From<i16> for ParamValue {
    fn from(item: i16) -> Self {
        ParamValue::SmallInteger(item)
    }
}

impl From<i32> for ParamValue {
    fn from(item: i32) -> Self {
        ParamValue::Integer(item.into())
    }
}

impl From<i64> for ParamValue {
    fn from(item: i64) -> Self {
        ParamValue::BigInteger(item)
    }
}

impl From<u16> for ParamValue {
    fn from(item: u16) -> Self {
        ParamValue::Integer(item.into())
    }
}

impl From<u32> for ParamValue {
    fn from(item: u32) -> Self {
        ParamValue::BigInteger(item.into())
    }
}

impl From<u64> for ParamValue {
    fn from(item: u64) -> Self {
        ParamValue::Numeric(Decimal::from(item))
    }
}

impl From<isize> for ParamValue {
    fn from(item: isize) -> Self {
        match isize::BITS {
            32 => ParamValue::Integer(item as i32),
            64 => ParamValue::BigInteger(item as i64),
            _ => unimplemented!(),
        }
    }
}

impl From<f32> for ParamValue {
    fn from(item: f32) -> Self {
        ParamValue::Real(item)
    }
}

impl From<f64> for ParamValue {
    fn from(item: f64) -> Self {
        ParamValue::BigReal(item)
    }
}

impl From<Decimal> for ParamValue {
    fn from(item: Decimal) -> Self {
        ParamValue::Numeric(item)
    }
}

impl From<bool> for ParamValue {
    fn from(item: bool) -> Self {
        ParamValue::Boolean(item)
    }
}

impl From<()> for ParamValue {
    fn from(_: ()) -> Self {
        ParamValue::Null
    }
}

pub trait IntoParamValue {
    fn into_param_value(self) -> ParamValue;
}

/// Implements [IntoParamValue] for types that implement [TryFrom] for [ParamValue].
impl<T: Into<ParamValue>> IntoParamValue for T {
    fn into_param_value(self) -> ParamValue {
        self.into()
    }
}

/// Query parameters
#[derive(Debug, Clone)]
pub enum Params {
    None,
    Positional(Vec<ParamValue>),
}

/// Types that implement this trait can be converted into [Params]
pub trait IntoParams {
    fn into_params(self) -> Params;
}

/// (Trivially) implements [IntoParams] for [Params]
impl IntoParams for Params {
    fn into_params(self) -> Params {
        self
    }
}

/// Implements [IntoParams] for references to [Params]
impl IntoParams for &Params {
    fn into_params(self) -> Params {
        self.clone()
    }
}

/// Implements [IntoParams] for an empty tuple. Always returns [Params::None].
impl IntoParams for () {
    fn into_params(self) -> Params {
        Params::None
    }
}

/// Implements [IntoParams] for fixed-length arrays of types that implement [IntoParamValue]
impl<T: IntoParamValue, const N: usize> IntoParams for [T; N] {
    fn into_params(self) -> Params {
        self.into_iter().collect::<Vec<_>>().into_params()
    }
}

/// Implements [IntoParams] for references to fixed-length arrays of types that implement
/// [IntoParamValue]
impl<T: IntoParamValue + Clone, const N: usize> IntoParams for &[T; N] {
    fn into_params(self) -> Params {
        self.iter().cloned().collect::<Vec<_>>().into_params()
    }
}

/// Implements [IntoParams] for vectors of types that implement [IntoParamValue]
impl<T: IntoParamValue> IntoParams for Vec<T> {
    fn into_params(self) -> Params {
        let values = self
            .into_iter()
            .map(|i| i.into_param_value())
            .collect::<Vec<_>>();
        Params::Positional(values)
    }
}

/// Converts a list of assorted types implementing [IntoParamValue] into [Params]
#[macro_export]
macro_rules! params {
    () => {
       ()
    };
    ($($value:expr),* $(,)?) => {{
        use $crate::core::IntoParamValue;
        [$($value.into_param_value()),*]

    }};
}

pub trait DbQuery {
    /// Get the kind of SQL database: SQLite or PostgreSQL.
    fn kind(&self) -> DbKind;

    /// Execute a SQL command, without a return value.
    fn execute(
        &self,
        sql: &str,
        params: impl IntoParams + Send,
    ) -> impl Future<Output = Result<(), DbError>> + Send;

    /// Sequentially execute a semicolon-delimited list of statements, without parameters.
    fn execute_batch(&self, sql: &str) -> impl Future<Output = Result<(), DbError>> + Send;

    /// Execute a SQL command, returning a vector of JSON rows.
    fn query(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<Vec<JsonRow>, DbError>> + Send;

    /// Execute a SQL command, returning a single JSON row.
    fn query_row(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<JsonRow, DbError>> + Send;

    /// Execute a SQL command, returning a single JSON value.
    fn query_value(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<JsonValue, DbError>> + Send;

    /// Execute a SQL command, returning a single string.
    fn query_string(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<String, DbError>> + Send;

    /// Execute a SQL command, returning a single unsigned integer.
    fn query_u64(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<u64, DbError>> + Send;

    /// Execute a SQL command, returning a single signed integer.
    fn query_i64(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<i64, DbError>> + Send;

    /// Execute a SQL command, returning a single float.
    fn query_f64(
        &self,
        sql: &str,
        params: impl IntoParams + Send + 'static,
    ) -> impl Future<Output = Result<f64, DbError>> + Send;
    /// Insert JSON rows into a table, returning the inserted rows.
    /// If a row does not have a key for a column, we treat it as NULL.
    fn insert(
        &self,
        table: &str,
        rows: &[&JsonRow],
    ) -> impl Future<Output = Result<Vec<JsonRow>, DbError>>;
}
