//! Error types

use std::fmt::Display;

/// The various error types that can be generated by rltbl_db.
#[derive(Debug)]
#[non_exhaustive] // We may add more specific error types in the future.
pub enum Error {
    /////////////////////////////
    // Internal error types:
    /////////////////////////////
    /// An error that occurred while connecting to a database.
    ConnectError(String),
    /// An error in the input to a function.
    InputError(String),
    /// An error related to the content of retrieved data.
    DataError(String),
    /// An error related to the data type of a value.
    DatatypeError(String),
    /// An error that occurred while attempting to parse a SQL string.
    ParseError(String),
    /// An error finding or converting a value.
    ValueError(String),

    /////////////////////////////
    // Upstream error types:
    /////////////////////////////
    /// An error that occurred while processing input/output.
    IOError(std::io::Error),

    /// An error that occurred while writing or reading a CSV (or TSV) file.
    CSVError(csv::Error),

    /// An error that occurred when trying to convert one primitive rust type to another.
    IntegerConversionError(std::num::TryFromIntError),

    /// An error that occurred when trying to convert a primitive type to a [rust_decimal::Decimal].
    DecimalConversionError(rust_decimal::Error),

    // See https://stackoverflow.com/questions/67830696/
    //             what-is-the-point-of-an-infallible-result-over-just-returning-the-ok-branch
    // for an explanation of the rationale behind Infallible. Essentially it's a convenience
    // to allow for treating generics consistently.
    /// An error that occurred (impossibly) as the result of an [std::convert::Infallible]
    /// operation.
    InfallibleError(std::convert::Infallible),

    /// An error that occurred during serialization or deserialization.
    SerdeError(String),

    /// An error orginating from the database.
    DatabaseError(DatabaseError),
}

/// An abstraction over the kinds of errors originating in database driver modules.
#[derive(Debug)]
pub enum DatabaseError {
    /// Undifferentiated database error.
    Error(String),

    /// Failure to build a pool.
    BuildError(String),

    /// Failure to create a pool from a given configuration.
    CreatePoolError(String),

    /// Failure to retrieve a pool.
    PoolError(String),

    /// Failure to interact with a pool.
    InteractError(String),
}

// Implement std::error::Error for our error types:
impl std::error::Error for Error {}
impl std::error::Error for DatabaseError {}

// Implement std::fmt::Display for our error types:
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConnectError(err)
            | Error::DataError(err)
            | Error::InputError(err)
            | Error::DatatypeError(err)
            | Error::ParseError(err)
            | Error::ValueError(err)
            | Error::SerdeError(err) => write!(f, "{err}"),
            Error::IOError(err) => write!(f, "{err}"),
            Error::CSVError(err) => write!(f, "{err}"),
            Error::InfallibleError(err) => write!(f, "{err}"),
            Error::IntegerConversionError(err) => write!(f, "{err}"),
            Error::DecimalConversionError(err) => write!(f, "{err}"),
            Error::DatabaseError(err) => write!(f, "{err}"),
        }
    }
}

impl std::fmt::Display for DatabaseError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            DatabaseError::Error(err)
            | DatabaseError::BuildError(err)
            | DatabaseError::CreatePoolError(err)
            | DatabaseError::PoolError(err)
            | DatabaseError::InteractError(err) => write!(f, "{err}"),
        }
    }
}

// Anything that implements Into<DatabaseError> is also an Error.
impl<T: Into<DatabaseError>> From<T> for Error {
    fn from(err: T) -> Error {
        Error::DatabaseError(err.into())
    }
}

// Serialization / Deserialization error implementations:
impl serde::ser::Error for Error {
    fn custom<T>(msg: T) -> Self
    where
        T: Display,
    {
        Error::SerdeError(msg.to_string())
    }
}

impl serde::de::Error for Error {
    fn custom<T>(msg: T) -> Self
    where
        T: Display,
    {
        Error::SerdeError(msg.to_string())
    }
}

// Conversions to and from our error types and various other error types.
impl From<&str> for DatabaseError {
    fn from(err: &str) -> DatabaseError {
        DatabaseError::Error(err.to_string())
    }
}

impl From<String> for DatabaseError {
    fn from(err: String) -> DatabaseError {
        DatabaseError::Error(err)
    }
}

impl From<std::io::Error> for Error {
    fn from(err: std::io::Error) -> Error {
        Error::IOError(err.into())
    }
}

impl From<serde_json::Error> for Error {
    fn from(err: serde_json::Error) -> Error {
        use serde_json::error::Category;
        match err.classify() {
            Category::Io => Error::IOError(err.into()),
            Category::Syntax | Category::Data | Category::Eof => Error::SerdeError(err.to_string()),
        }
    }
}

impl From<csv::Error> for Error {
    fn from(err: csv::Error) -> Error {
        Error::IOError(err.into())
    }
}

impl From<std::convert::Infallible> for Error {
    fn from(err: std::convert::Infallible) -> Error {
        Error::InfallibleError(err)
    }
}

impl From<std::num::TryFromIntError> for Error {
    fn from(err: std::num::TryFromIntError) -> Error {
        Error::IntegerConversionError(err)
    }
}

impl From<rust_decimal::Error> for Error {
    fn from(err: rust_decimal::Error) -> Error {
        Error::DecimalConversionError(err)
    }
}
