//! Error types

/// The various error types that can be generated by rltbl_db.
#[derive(Debug)]
#[non_exhaustive] // We may add more specific error types in the future.
pub enum Error {
    /////////////////////////////
    // Internal error types:
    /////////////////////////////
    /// An error that occurred while connecting to a database.
    ConnectError(String),
    /// An error in the arguments to a function that accessed the database.
    InputError(String),
    /// An error in the data retrieved from the database.
    DataError(String),
    /// An error that originated from the database.
    DatabaseError(String),
    /// An error with the data type of a value.
    DatatypeError(String),
    /// An error that occurred while attempting to parse a SQL string.
    ParseError(String),
    /// An error finding or converting a value.
    ValueError(String),

    /////////////////////////////
    // Upstream error types:
    /////////////////////////////
    /// An error that occurred when trying to convert one primitive rust type to another.
    IntegerConversionError(std::num::TryFromIntError),

    /// An error that occurred when trying to convert a primitive type to a [rust_decimal::Decimal].
    DecimalConversionError(rust_decimal::Error),

    /// TODO: Not sure if this is really needed. It's basically guaranteed never to occur?
    /// It's the result of a call like: i16::try_from(1_i16) which in principle should never fail.
    InfallibleError(std::convert::Infallible),

    // TODO: Replace this with the upstream error:
    /// An error that occurred during serialization or deserialization.
    SerdeError(String),

    #[cfg(feature = "rusqlite")]
    /// TODO: add docstring.
    DeadpoolRusqliteError(deadpool_sqlite::rusqlite::Error),
    #[cfg(feature = "rusqlite")]
    /// TODO: add docstring.
    DeadpoolRusqliteBuildError(deadpool_sqlite::BuildError),
    #[cfg(feature = "rusqlite")]
    /// TODO: add docstring.
    DeadpoolRusqliteCreatePoolError(deadpool_sqlite::CreatePoolError),
    #[cfg(feature = "rusqlite")]
    /// TODO: Add doctring.
    DeadpoolRusqlitePoolError(deadpool_sqlite::PoolError),
    #[cfg(feature = "rusqlite")]
    /// TODO: Add doctring.
    DeadpoolRusqliteInteractError(deadpool_sqlite::InteractError),

    #[cfg(feature = "tokio-postgres")]
    /// TODO: Add docstring
    DeadpoolPostgresError(deadpool_postgres::tokio_postgres::Error),
    #[cfg(feature = "tokio-postgres")]
    /// TODO: Add docstring
    DeadpoolPostgresCreatePoolError(deadpool_postgres::CreatePoolError),
    #[cfg(feature = "tokio-postgres")]
    /// TODO: Add docstring
    DeadpoolPostgresPoolError(deadpool_postgres::PoolError),
    //
    // TODO: libsql errors
    //
    // TODO: serde errors.
}

impl std::error::Error for Error {}

impl From<std::convert::Infallible> for Error {
    fn from(err: std::convert::Infallible) -> Error {
        Error::InfallibleError(err)
    }
}

impl From<std::num::TryFromIntError> for Error {
    fn from(err: std::num::TryFromIntError) -> Error {
        Error::IntegerConversionError(err)
    }
}

impl From<rust_decimal::Error> for Error {
    fn from(err: rust_decimal::Error) -> Error {
        Error::DecimalConversionError(err)
    }
}

// Rusqlite error implementations:

#[cfg(feature = "rusqlite")]
impl From<deadpool_sqlite::rusqlite::Error> for Error {
    fn from(err: deadpool_sqlite::rusqlite::Error) -> Error {
        Error::DeadpoolRusqliteError(err)
    }
}

#[cfg(feature = "rusqlite")]
impl From<deadpool_sqlite::BuildError> for Error {
    fn from(err: deadpool_sqlite::BuildError) -> Error {
        Error::DeadpoolRusqliteBuildError(err)
    }
}

#[cfg(feature = "rusqlite")]
impl From<deadpool_sqlite::CreatePoolError> for Error {
    fn from(err: deadpool_sqlite::CreatePoolError) -> Error {
        Error::DeadpoolRusqliteCreatePoolError(err)
    }
}

#[cfg(feature = "rusqlite")]
impl From<deadpool_sqlite::PoolError> for Error {
    fn from(err: deadpool_sqlite::PoolError) -> Error {
        Error::DeadpoolRusqlitePoolError(err)
    }
}

#[cfg(feature = "rusqlite")]
impl From<deadpool_sqlite::InteractError> for Error {
    fn from(err: deadpool_sqlite::InteractError) -> Error {
        Error::DeadpoolRusqliteInteractError(err)
    }
}

// Tokio-postgres error implementations:

#[cfg(feature = "tokio-postgres")]
impl From<deadpool_postgres::tokio_postgres::Error> for Error {
    fn from(err: deadpool_postgres::tokio_postgres::Error) -> Error {
        Error::DeadpoolPostgresError(err)
    }
}

#[cfg(feature = "tokio-postgres")]
impl From<deadpool_postgres::CreatePoolError> for Error {
    fn from(err: deadpool_postgres::CreatePoolError) -> Error {
        Error::DeadpoolPostgresCreatePoolError(err)
    }
}

#[cfg(feature = "tokio-postgres")]
impl From<deadpool_postgres::PoolError> for Error {
    fn from(err: deadpool_postgres::PoolError) -> Error {
        Error::DeadpoolPostgresPoolError(err)
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Error::ConnectError(err)
            | Error::DataError(err)
            | Error::InputError(err)
            | Error::DatabaseError(err)
            | Error::DatatypeError(err)
            | Error::ParseError(err)
            | Error::ValueError(err)
            | Error::SerdeError(err) => write!(f, "{err}"),
            Error::InfallibleError(err) => write!(f, "{err}"),
            Error::IntegerConversionError(err) => write!(f, "{err}"),
            Error::DecimalConversionError(err) => write!(f, "{err}"),
            #[cfg(feature = "rusqlite")]
            Error::DeadpoolRusqliteError(err) => write!(f, "{err}"),
            #[cfg(feature = "rusqlite")]
            Error::DeadpoolRusqliteBuildError(err) => write!(f, "{err}"),
            #[cfg(feature = "rusqlite")]
            Error::DeadpoolRusqliteCreatePoolError(err) => write!(f, "{err}"),
            #[cfg(feature = "rusqlite")]
            Error::DeadpoolRusqlitePoolError(err) => write!(f, "{err}"),
            #[cfg(feature = "rusqlite")]
            Error::DeadpoolRusqliteInteractError(err) => write!(f, "{err}"),
            #[cfg(feature = "tokio-postgres")]
            Error::DeadpoolPostgresError(err) => write!(f, "{err}"),
            #[cfg(feature = "tokio-postgres")]
            Error::DeadpoolPostgresCreatePoolError(err) => write!(f, "{err}"),
            #[cfg(feature = "tokio-postgres")]
            Error::DeadpoolPostgresPoolError(err) => write!(f, "{err}"),
        }
    }
}

// TODO: anyhow error?

// MC: Actually I have been meaning to ask you for awhile now why we decided to forget
// AnyHow in rltbl_db. I have found it pretty useful in the past.

// JO: Anyhow is convenient and I use it in Relatable, which is designed as an application.
// But the idea is that this is a library, and should expose more error information to the user,
// so the user has the opportunity to handle it.
// Here's one view: https://www.lpalmieri.com/posts/error-handling-rust/#anyhow-or-thiserror
// I'm not sure what the best approach is in this case.

// MC: I think it does make sense to not wrap errors in our case, for the reason you mentioned.
// Note, though, that the author of that page makes the following point:
//
// "Freedom comes at a price - the interface is more complex, users need to sift through 10+
// variants trying to figure out which (if any) deserve special handling."
//
// I think this is a good point in general, but I am not too concerned in our case.
// I would be more worried about this if some of the errors above did not implement Display.
// That was true of sqlx::Error, if I recall correctly, which was a source of some frustration,
// But in our case, all of the above errors implement Display so the user will at least be able
// to print the information.
